---
title: "Regression"
output: html_notebook
---


```{r}
library(MASS)
library(ISLR)
```

```{r}
names(Boston)
?Boston
```


```{r}
plot(medv~lstat, Boston)
```

```{r}
fit1 = lm(medv~lstat, data=Boston)
fit1
```


```{r}
summary(fit1)
```

```{r}
plot(medv~lstat, Boston)
abline(fit1, col='red')
```


```{r}

names(fit1)
confint(fit1)
predict(fit1, data.frame(lstat=c(5, 10, 15)), interval = "confidence")

```

Multiple linear regression

```{r}
fit2 = lm(medv~lstat+age, data=Boston)
summary(fit2)
```

```{r}
fit3 = lm(medv~., data=Boston)
summary(fit3)
```

```{r}
par(mfrow=c(2, 2))
plot(fit3)
```

```{r}
fit4=update(fit3,~.-age-indus)
summary(fit4)
```

Nonlinear terms

```{r}
fit5 = lm(medv~lstat*age, data=Boston)
summary(fit5)
```

```{r}
fit6 = lm(medv~lstat+I(lstat^2), data=Boston)
summary(fit6)
```

```{r}
attach(Boston)
par(mfrow=c(1, 1))
plot(medv~lstat)
points(lstat, fitted(fit6), col = 'red', pch = 20)
```

```{r}
fit7 = lm(medv~poly(lstat, 4), data=Boston)
summary(fit7)
```
```{r}
par(mfrow=c(1, 1))
plot(medv~lstat)
points(lstat, fitted(fit6), col = 'red', pch = 20)
points(lstat, fitted(fit7), col = 'blue', pch = 20)
plot(1:20, 1:20, pch=1:20, cex=2)
```

Qualitative predictors

```{r}
fix(Carseats)
```

```{r}
names(Carseats)
summary(Carseats)
```

```{r}
fi1 = lm(Sales~.+Income:Advertising+Age:Price, data=Carseats)
summary(fi1)
```

```{r}
contrasts(Carseats$ShelveLoc)
```


R function

```{r}
regplot = function(x, y){
  fit = lm(y~x)
  plot(x, y)
  abline(fit, col='red')
}
```
```{r}
attach(Carseats)
regplot(Price, Sales)
```

```{r}
regplot = function(x, y,...){
  fit = lm(y~x)
  plot(x, y,...)
  abline(fit, col='red')
}
```

```{r}
regplot(Price, Sales, xlab='Price', ylab='sale', col='blue', pch=20)
```

